# Generated by Django 5.2.3 on 2025-06-30 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmetadata',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
